Repository BOONG-O-BBANG/BOONG-O-BBANG_CLIENT, pull requests merged in 2023-09, with the labels that each got.

#25 [Feature] 로그인 페이지 디자인
  bob_client/src/assets/Whitelogo.png
  bob_client/src/assets/blacklogo.png
  bob_client/src/assets/bluelogo.png
  bob_client/src/components/Login.vue
  bob_client/src/page/LoginView.vue
Labels: ✨ Feature

#31 [Refactor] 페이지 디자인
  bob_client/src/assets/icon.png
  bob_client/src/assets/icon2.png
  bob_client/src/components/EditProfile.vue
  bob_client/src/components/Modal.vue
  bob_client/src/page/Alarm.vue
  bob_client/src/page/History.vue
  bob_client/src/page/Home.vue
  bob_client/src/page/List.vue
  bob_client/src/page/Main.vue
  bob_client/src/page/Menu.vue
  bob_client/src/page/MyPage.vue
  bob_client/src/page/MyProfile.vue
Labels: 🔨 Refactor

#38 [Feature] 회원가입 & 로그인 연동 #33
  bob_client/public/user.json
  bob_client/src/components/EditProfile.vue
  bob_client/src/components/Login.vue
  bob_client/src/components/Signup.vue
  bob_client/src/page/LoginView.vue
  bob_client/src/page/MyPage.vue
  bob_client/src/page/MyProfile.vue
  bob_client/src/typeuser.js
Labels: 🔨 Refactor, ✨ Feature

#39 [Feature] 메인페이지 구현
  bob_client/src/components/Login.vue
  bob_client/src/components/Modal.vue
  bob_client/src/components/Signup.vue
  bob_client/src/page/Home.vue
Labels: ✨ Feature

#41 [Feature] 룸메이트 찾기 페이지 구현
  bob_client/src/components/Modal.vue
  bob_client/src/page/Home.vue
  bob_client/src/page/List.vue
Labels: 🔨 Refactor, ✨ Feature

#43 Develop
  bob_client/src/components/EditProfile.vue
  bob_client/src/components/RateModal.vue
  bob_client/src/components/Signup.vue
  bob_client/src/page/Alarm.vue
  bob_client/src/page/History.vue
  bob_client/src/page/Home.vue
  bob_client/src/page/List.vue
  bob_client/src/page/MyProfile.vue
  bob_client/src/page/SmallMenu.vue
Labels: ✨ Feature

#49 Develop
  bob_client/src/components/Modal.vue
  bob_client/src/page/History.vue
  bob_client/src/page/Main.vue
Labels: 🔨 Refactor

#54 [BUG] api 수정
  bob_client/vue.config.js
Labels: 🌏 Deploy
