Repository BOONG-O-BBANG/BOONG-O-BBANG_CLIENT, pull requests merged in 2023-08, with the labels that each got.

#3 PR test 따라하기
  test01.txt
Labels: Test

#2 PR test
  test.txt
Labels: Test

#5 Feat/Init
  bob_client/.gitignore
  bob_client/README.md
  bob_client/babel.config.js
  bob_client/jsconfig.json
  bob_client/package-lock.json
  bob_client/package.json
  bob_client/public/favicon.ico
  bob_client/public/index.html
  bob_client/src/App.vue
  bob_client/src/assets/logo.png
  bob_client/src/components/HelloWorld.vue
  bob_client/src/main.js
  bob_client/vue.config.js
Labels: Feature, Setting

#6 Develop
  bob_client/.gitignore
  bob_client/README.md
  bob_client/babel.config.js
  bob_client/jsconfig.json
  bob_client/package-lock.json
  bob_client/package.json
  bob_client/public/favicon.ico
  bob_client/public/index.html
  bob_client/src/App.vue
  bob_client/src/assets/logo.png
  bob_client/src/components/HelloWorld.vue
  bob_client/src/main.js
  bob_client/vue.config.js
Labels: Feature, Setting

#16 Develop
  bob_client/src/components/Login.vue
  bob_client/src/components/Modal.vue
  bob_client/src/components/Signup.vue
  bob_client/src/page/List.vue
  bob_client/src/page/Main.vue
Labels: 🐞 BugFix, ✨ Feature
